on:
  release:
    types:
      - "published"

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: get-pom-version
        id: pom-version
        uses: CptMokoena/maven-get-version-action@main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.pom-version.outputs.version }}
          gh release upload "${{ github.event.release.tag_name }}" \
            "./yuanluServerDo-bukkit/target/yuanluServerDo-bukkit-${VERSION}.jar" \
            "./yuanluServerDo-bukkit-bungeecord/target/yuanluServerDo-bukkit-bungeecord-${VERSION}.jar" \
            "./yuanluServerDo-bukkit-velocity/target/yuanluServerDo-bukkit-velocity-${VERSION}.jar" \
            "./yuanluServerDo-bungeecord/target/yuanluServerDo-bungeecord-${VERSION}.jar" \
            "./yuanluServerDo-velocity/target/yuanluServerDo-velocity-${VERSION}.jar" \
            --repo "${{ github.repository }}"
